[build]
  publish = "public"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["sequelize", "pg", "pg-hstore", "pg-native"]

# Route Express API
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api"
  status = 200

# Route DB test
[[redirects]]
  from = "/db"
  to = "/.netlify/functions/db"
  status = 200
