[build]
  command = "npm run build" # If you have a frontend build step
  publish = "build"         # Directory where your static frontend files are

[functions]
  directory = "functions"   # Specifies the directory for your Netlify Functions